logging:
  receivers:
    file-logs:
      type: files
      include_paths:
      - /var/log/myapp
      record_log_file_path: true

    processors:
        parser-process:
          type: parse_json
          time_key: time
          time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    service:
        pipelines:
          default_pipeline:
            receivers: [file-logs]
            processors: [parser-process]