logging:
  receivers:
    custom-file:
      type: files
      include_paths:
      - /var/log/myapp
      record_log_file_path: true
  service:
    pipelines:
      pipeline1:
        receivers: [custom-file]
