logging:
  receivers:
    custom_file1:
      type: files
      include_paths:
      - /var/log/myapp/my-app.log
      record_log_file_path: true
  processors:
    parse_java_multiline:
      type: parse_json
      time_key: timestamp
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    move_severity:
      type: modify_fields
      fields:
        severity:
          copy_from: jsonPayload.level
  service:
    pipelines:
      pipeline1:
        receivers: [custom_file1]
        processors: [parse_java_multiline, extract_structure, move_severity]