name: GCP CLI

on:
  pull_request_target:
    types:  ["opened", "reopened", "synchronize"]

jobs:
  gcloud-cli:
    name: gcloud-cli
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    steps:
      - name: 'auth'
        uses: 'google-github-actions/auth@v2'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
