name: GCP CLI

on:
  pull_request:
    types:  ["opened", "reopened", "synchronize"]
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.REPO_VAR }}
jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: 'Read'
        run: echo "Reading variables from file"
      - name: 'ok'
        run: echo "$cred"
        env:
          cred: ${{ secrets.GCP_SA_KEY }}
      - name: 'auth'
        uses: 'google-github-actions/auth@v2'
        env: # 
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    
