name: GCP CLI

on:
  pull_request_target:
    types:  ["opened", "reopened", "synchronize"]

jobs:
  gcloud-cli:
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        
