name: GCP CLI

on:
  pull_request_target:
    types:  ["opened", "reopened", "synchronize"]

env:
  PROJECT_ID: cloud-nw-dev # TODO: update Google Cloud project id
  # SERVICE: YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  # REGION: us-east1 # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
