# # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# # This workflow uses actions that are not certified by GitHub.
# # They are provided by a third-party and are governed by
# # separate terms of service, privacy policy, and support
# # documentation.

# name: Java CI with Maven

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         cache: maven
#     - name: List directory contents
#       run: ls -R
#     - name: Build with Maven
#       run: mvn -B package --file ./webapp/pom.xml

name: Java CI with Maven

on:
  pull_request:
    types: ["opened"]
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: List directory contents
      run: ls -R
    - name: Build with Maven
      run: mvn -B package --file ./webapp/pom.xml
      
    - name: Check if compilation was successful
      run: mvn compile

  # merge:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Check out the code
  #       uses: actions/checkout@v2

  #     - name: Merge pull request if build is successful
  #       run: |
  #         # Check if the build job was successful
  #         if [ ${{ needs.build.result }} == 'success' ]; then
  #           # Merge the pull request
  #           git merge --no-ff ${{ github.event.pull_request.head.ref }}
  #         else
  #           # Print a message and exit with a non-zero code to fail the workflow
  #           echo "Build failed, cannot merge the pull request."
  #           exit 1
  #         fi

# Restrict merging to branch protection rules
# Ensure 'main' branch is protected and require status checks to pass before merging
# This configuration should be done in the repository settings on GitHub


