name: Java CI with Maven

on:
  pull_request_target:
    types:  ["opened", "reopened", "synchronize"]


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: List directory contents
      run: ls -R
    - name: Build with Maven
      run: mvn -B compile --file ./webapp/pom.xml
    
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Tests
      run: mvn -B test --file ./webapp/pom.xml

  packer:
    name: packer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y packer
      
      - name: List directory contents
        run: ls -R

      - name:  Packer INIT
        run: packer init ./packer/pck-img.json.pkr.hcl
        
      - name: Format Packer template
        run: packer fmt ./packer/pck-img.json.pkr.hcl

      - name: Validate Packer template
        run: packer validate ./packer/pck-img.json.pkr.hcl
    
  gcloud-cli:
    name: gcloud-cli
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    steps:
      - name: 'auth'
        uses: 'google-github-actions/auth@v2'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
